CREATE TABLE `t_csys_teaching_plan` (
                                        `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                        `root_plan_id` bigint DEFAULT NULL COMMENT '同一教学计划版本根ID',
                                        `source_course_id` bigint NOT NULL COMMENT '总库课程ID，关联t_csys_course.id',
                                        `plan_type` tinyint NOT NULL COMMENT '教学计划类型(与课程类型同字典值):1课程 2实践训练课目 3实验课程 4实践项目',
                                        `version` varchar(20) DEFAULT NULL COMMENT '教学计划版本，如2026、V1.0',
                                        `current_flag` tinyint NOT NULL DEFAULT 1 COMMENT '是否当前版本：1是 0否',
                                        `enabled_term` varchar(50) DEFAULT NULL COMMENT '启用时间，如2026年春季学期',
                                        `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0草稿 1审核中 2通过 3退回 9停用',
                                        `source_course_name` varchar(255) DEFAULT NULL COMMENT '总库课程名称快照',
                                        `source_course_code` varchar(50) DEFAULT NULL COMMENT '总库课程编号快照',
                                        `source_course_en_name` varchar(255) DEFAULT NULL COMMENT '总库课程英文名快照',
                                        `source_hours` decimal(8,2) DEFAULT NULL COMMENT '总库课程总学时快照',
                                        `source_teach_hours` decimal(8,2) DEFAULT NULL COMMENT '总库课程讲授学时快照',
                                        `source_practice_hours` decimal(8,2) DEFAULT NULL COMMENT '总库课程实践/实验学时快照',
                                        `source_credit` decimal(8,2) DEFAULT NULL COMMENT '总库课程学分快照',
                                        `score_rule` text COMMENT '计分规则',
                                        `file_id` varchar(255) DEFAULT NULL COMMENT '生成或上传文件ID',
                                        `file_name` varchar(255) DEFAULT NULL COMMENT '文件名称',
                                        `download_url` varchar(500) DEFAULT NULL COMMENT '下载地址',
                                        `preview_url` varchar(500) DEFAULT NULL COMMENT '预览地址',
                                        `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                        `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                        `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                        `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                        `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                        `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识：0正常 2删除',
                                        PRIMARY KEY (`id`),
                                        UNIQUE KEY `uk_tp_source_course_plan_type` (`source_course_id`, `plan_type`, `sysflag`),
                                        KEY `idx_tp_source_course` (`source_course_id`),
                                        KEY `idx_tp_root` (`root_plan_id`),
                                        KEY `idx_tp_type_status` (`plan_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课程教学计划主表';

CREATE TABLE `t_csys_teaching_plan_context` (
                                                `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                `source_course_id` bigint NOT NULL COMMENT '总库课程ID',
                                                `quote_course_id` bigint NOT NULL COMMENT '调用课程ID，t_csys_course.id',
                                                `scheme_id` bigint NOT NULL COMMENT '培养方案ID',
                                                `schedule_id` bigint DEFAULT NULL COMMENT '培养方案排课ID',
                                                `scheme_name` varchar(255) DEFAULT NULL COMMENT '培养方案名称快照',
                                                `scheme_version` varchar(20) DEFAULT NULL COMMENT '培养方案版本快照',
                                                `education_level` varchar(225) DEFAULT NULL COMMENT '适用对象/培养层次',
                                                `object_type` varchar(50) DEFAULT NULL COMMENT '培养对象类型',
                                                `education` varchar(50) DEFAULT NULL COMMENT '学历',
                                                `academic_type` varchar(50) DEFAULT NULL COMMENT '学制类型',
                                                `duration_type` varchar(50) DEFAULT NULL COMMENT '学制年限',
                                                `degree` varchar(50) DEFAULT NULL COMMENT '授予学位类型',
                                                `college_id` bigint DEFAULT NULL COMMENT '学院ID',
                                                `category_id` bigint DEFAULT NULL COMMENT '门类ID',
                                                `major_id` bigint DEFAULT NULL COMMENT '专业ID',
                                                `sub_major_id` bigint DEFAULT NULL COMMENT '专业方向ID',
                                                `course_module` varchar(64) DEFAULT NULL COMMENT '课程模块编码',
                                                `course_module_children` varchar(64) DEFAULT NULL COMMENT '课程子模块编码',
                                                `semester_schedule` varchar(64) DEFAULT NULL COMMENT '学期安排',
                                                `term` tinyint DEFAULT NULL COMMENT '开课学期',
                                                `course_attr` varchar(64) DEFAULT NULL COMMENT '修读性质',
                                                `time_arrange` varchar(255) DEFAULT NULL COMMENT '时间安排',
                                                `hours` decimal(8,2) DEFAULT NULL COMMENT '上下文总学时',
                                                `teach_hours` decimal(8,2) DEFAULT NULL COMMENT '上下文讲授学时',
                                                `practice_hours` decimal(8,2) DEFAULT NULL COMMENT '上下文实践/实验学时',
                                                `credits` decimal(8,2) DEFAULT NULL COMMENT '上下文学分',
                                                `sync_time` datetime DEFAULT NULL COMMENT '从课程调用关系同步时间',
                                                `sync_flag` tinyint NOT NULL DEFAULT 1 COMMENT '同步状态：1有效 2调用关系已失效',
                                                `sort` int DEFAULT 1 COMMENT '排序',
                                                `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                PRIMARY KEY (`id`),
                                                UNIQUE KEY `uk_tp_context` (`plan_id`,`quote_course_id`,`scheme_id`),
                                                KEY `idx_tp_context_source` (`source_course_id`),
                                                KEY `idx_tp_context_scheme` (`scheme_id`),
                                                KEY `idx_tp_context_quote_course` (`quote_course_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划调用课程上下文';

CREATE TABLE `t_csys_scheme_course_ref_graduation` (
                                                       `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                       `scheme_id` bigint NOT NULL COMMENT '培养方案ID',
                                                       `quote_course_id` bigint NOT NULL COMMENT '调用课程ID，t_csys_course.id',
                                                       `source_course_id` bigint DEFAULT NULL COMMENT '总库课程ID快照',
                                                       `graduation_id` bigint NOT NULL COMMENT '方案内毕业标准ID，t_csys_std_graduation.id',
                                                       `source_graduation_id` bigint DEFAULT NULL COMMENT '毕业标准总库ID，通常为t_csys_std_graduation.source_id',
                                                       `college_id` bigint DEFAULT NULL COMMENT '学院ID',
                                                       `category_id` bigint DEFAULT NULL COMMENT '门类ID',
                                                       `major_id` bigint DEFAULT NULL COMMENT '专业ID',
                                                       `sub_major_id` bigint DEFAULT NULL COMMENT '专业方向ID',
                                                       `support_level` varchar(64) DEFAULT NULL COMMENT '支撑强度/支撑程度字典编码，可选',
                                                       `graduation_code` varchar(100) DEFAULT NULL COMMENT '毕业标准编码快照',
                                                       `graduation_name` varchar(500) DEFAULT NULL COMMENT '毕业标准名称快照',
                                                       `sort` int DEFAULT 1 COMMENT '排序',
                                                       `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                       `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                       `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                       `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                       `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                       `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识：0正常 2删除',
                                                       PRIMARY KEY (`id`),
                                                       UNIQUE KEY `uk_scheme_course_graduation` (`scheme_id`,`quote_course_id`,`graduation_id`),
                                                       KEY `idx_scrg_quote_course` (`quote_course_id`),
                                                       KEY `idx_scrg_source_course` (`source_course_id`),
                                                       KEY `idx_scrg_graduation` (`graduation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='培养方案调用课程毕业要求关联表';

CREATE TABLE `t_csys_teaching_plan_teacher` (
                                                `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                `teacher_id` varchar(100) DEFAULT NULL COMMENT '教员ID(外库字符串主键)',
                                                `teacher_name` varchar(100) NOT NULL COMMENT '教员姓名',
                                                `professional_title` varchar(100) DEFAULT NULL COMMENT '职称',
                                                `duty` varchar(100) DEFAULT NULL COMMENT '职责',
                                                `lecture_content` text COMMENT '主讲内容',
                                                `sort` int DEFAULT 1 COMMENT '排序',
                                                `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                PRIMARY KEY (`id`),
                                                KEY `idx_tp_teacher_plan` (`plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划教员团队';

CREATE TABLE `t_csys_teaching_plan_section` (
                                                `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                `section_code` varchar(64) NOT NULL COMMENT '章节编码：task_background、overall_design等',
                                                `section_title` varchar(255) DEFAULT NULL COMMENT '章节标题',
                                                `content` longtext COMMENT '章节内容',
                                                `sort` int DEFAULT 1 COMMENT '排序',
                                                `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                PRIMARY KEY (`id`),
                                                KEY `idx_tp_section_plan` (`plan_id`),
                                                KEY `idx_tp_section_code` (`section_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划文本章节';

CREATE TABLE `t_csys_teaching_plan_objective` (
                                                  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                  `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                  `scheme_id` bigint DEFAULT NULL COMMENT '培养方案ID，公共基础课程为NULL',
                                                  `major_id` bigint DEFAULT NULL COMMENT '专业ID',
                                                  `objective_type_code` varchar(64) NOT NULL COMMENT '目标类型字典编码：知识目标/能力目标/素质目标',
                                                  `objective_type_name` varchar(100) DEFAULT NULL COMMENT '目标类型名称快照',
                                                  `content` text NOT NULL COMMENT '目标内容，手工录入',
                                                  `source_mode` tinyint DEFAULT 2 COMMENT '来源方式：2手工录入',
                                                  `weight` decimal(8,4) DEFAULT NULL COMMENT '课程目标权重，普通课程目标合计为1',
                                                  `sort` int DEFAULT 1 COMMENT '排序',
                                                  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                  `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                  `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                  `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                  PRIMARY KEY (`id`),
                                                  KEY `idx_tp_obj_plan` (`plan_id`),
                                                  KEY `idx_tp_obj_scheme` (`scheme_id`),
                                                  KEY `idx_tp_obj_type` (`objective_type_code`),
                                                  KEY `idx_tp_obj_plan_scheme_type` (`plan_id`,`scheme_id`,`objective_type_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划目标';

CREATE TABLE `t_csys_teaching_plan_objective_ref` (
                                                      `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                      `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                      `objective_id` bigint NOT NULL COMMENT '教学计划目标ID',
                                                      `scheme_course_graduation_id` bigint DEFAULT NULL COMMENT '培养方案调用课程毕业要求关联ID，优先关联t_csys_scheme_course_ref_graduation.id',
                                                      `quote_course_id` bigint NOT NULL COMMENT '调用课程ID快照',
                                                      `scheme_id` bigint DEFAULT NULL COMMENT '培养方案ID快照，公共基础课程为NULL',
                                                      `graduation_id` bigint NOT NULL COMMENT '方案内毕业标准ID，t_csys_std_graduation.id',
                                                      `source_graduation_id` bigint DEFAULT NULL COMMENT '毕业标准总库ID，通常为t_csys_std_graduation.source_id',
                                                      `graduation_code` varchar(100) DEFAULT NULL COMMENT '毕业标准编码快照',
                                                      `graduation_name` varchar(500) DEFAULT NULL COMMENT '毕业标准名称快照',
                                                      `graduation_bind_source` varchar(64) DEFAULT NULL COMMENT '绑定来源：scheme_course_ref或course_ref_graduation',
                                                      `support_desc` varchar(1000) DEFAULT NULL COMMENT '支撑说明',
                                                      `sort` int DEFAULT 1 COMMENT '排序',
                                                      `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                      `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                      `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                      `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                      `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                      `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                      PRIMARY KEY (`id`),
                                                      KEY `idx_tp_obj_ref_plan` (`plan_id`),
                                                      KEY `idx_tp_obj_ref_obj` (`objective_id`),
                                                      KEY `idx_tp_obj_ref_scheme_course_graduation` (`scheme_course_graduation_id`),
                                                      KEY `idx_tp_obj_ref_scheme_course` (`scheme_id`,`quote_course_id`),
                                                      KEY `idx_tp_obj_ref_graduation` (`graduation_id`),
                                                      UNIQUE KEY `uk_tp_obj_ref` (`objective_id`,`scheme_id`,`graduation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划目标支撑毕业要求';

CREATE TABLE `t_csys_teaching_plan_content` (
                                                `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                `parent_id` bigint DEFAULT NULL COMMENT '父级内容ID',
                                                `content_type` tinyint NOT NULL COMMENT '内容类型：1专题 2课程项目 3实验 4大作业 5训练模块 6模块内容',
                                                `title` varchar(255) DEFAULT NULL COMMENT '专题/模块/内容名称',
                                                `content` text COMMENT '内容说明',
                                                `purpose` text COMMENT '目的',
                                                `hours` decimal(8,2) DEFAULT NULL COMMENT '学时',
                                                `time_arrange` varchar(100) DEFAULT NULL COMMENT '时间安排，如1天',
                                                `sort` int DEFAULT 1 COMMENT '排序',
                                                `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                PRIMARY KEY (`id`),
                                                KEY `idx_tp_content_plan` (`plan_id`),
                                                KEY `idx_tp_content_parent` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划内容与学时安排';

CREATE TABLE `t_csys_teaching_plan_target_design` (
                                                      `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                      `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                      `context_id` bigint DEFAULT NULL COMMENT '教学计划调用上下文ID；按tab维护时填写',
                                                      `design_type_code` varchar(64) NOT NULL COMMENT '设计类型字典编码：知识目标/能力目标/素质目标',
                                                      `objective_id` bigint DEFAULT NULL COMMENT '对应教学计划目标ID',
                                                      `knowledge_unit_id` bigint DEFAULT NULL COMMENT '知识单元ID，t_csys_course_knowledge_unit.id',
                                                      `knowledge_unit_name` varchar(255) DEFAULT NULL COMMENT '知识单元名称快照',
                                                      `knowledge_point_id` bigint DEFAULT NULL COMMENT '知识点ID，t_csys_course_knowledge_point.id',
                                                      `knowledge_point_name` varchar(500) DEFAULT NULL COMMENT '知识点名称快照',
                                                      `observation_point` text COMMENT '观测点',
                                                      `content_ids` json DEFAULT NULL COMMENT '关联教学内容ID数组',
                                                      `content_text` text COMMENT '教学内容文本快照',
                                                      `teaching_link` varchar(255) DEFAULT NULL COMMENT '教学环节',
                                                      `teaching_method` varchar(255) DEFAULT NULL COMMENT '教法',
                                                      `learning_method` varchar(255) DEFAULT NULL COMMENT '学法',
                                                      `hours` decimal(8,2) DEFAULT NULL COMMENT '学时',
                                                      `teaching_design` text COMMENT '教学设计',
                                                      `sort` int DEFAULT 1 COMMENT '排序',
                                                      `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                      `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                      `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                      `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                      `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                      `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                      PRIMARY KEY (`id`),
                                                      KEY `idx_tp_design_plan` (`plan_id`),
                                                      KEY `idx_tp_design_context` (`context_id`),
                                                      KEY `idx_tp_design_obj` (`objective_id`),
                                                      KEY `idx_tp_design_knowledge` (`knowledge_unit_id`,`knowledge_point_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学目标达成设计';

CREATE TABLE `t_csys_teaching_plan_practice_item` (
                                                      `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                      `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                      `item_type` tinyint NOT NULL COMMENT '项目类型：1实验 2实践项目 3设计实验 4验证实验',
                                                      `name` varchar(255) NOT NULL COMMENT '项目名称',
                                                      `hours` decimal(8,2) DEFAULT NULL COMMENT '学时',
                                                      `group_info` varchar(255) DEFAULT NULL COMMENT '分组情况',
                                                      `experiment_nature` varchar(100) DEFAULT NULL COMMENT '实验性质',
                                                      `study_nature` varchar(100) DEFAULT NULL COMMENT '修读性质',
                                                      `sort` int DEFAULT 1 COMMENT '排序',
                                                      `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                      `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                      `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                      `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                      `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                      `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                      PRIMARY KEY (`id`),
                                                      KEY `idx_tp_item_plan` (`plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划实验/实践项目';

CREATE TABLE `t_csys_teaching_plan_practice_item_detail` (
                                                             `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                             `item_id` bigint NOT NULL COMMENT '实验/实践项目ID',
                                                             `detail_type` varchar(64) NOT NULL COMMENT '明细类型：purpose_task、ability_point、principle、content_requirement、result_requirement、teaching_design、complex_problem、main_task、overall_design、outcome_requirement',
                                                             `objective_id` bigint DEFAULT NULL COMMENT '训练能力点或支撑目标ID',
                                                             `content` longtext COMMENT '明细内容',
                                                             `sort` int DEFAULT 1 COMMENT '排序',
                                                             PRIMARY KEY (`id`),
                                                             KEY `idx_tp_item_detail_item` (`item_id`),
                                                             KEY `idx_tp_item_detail_obj` (`objective_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='实验/实践项目明细';

CREATE TABLE `t_csys_teaching_plan_assessment` (
                                                   `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                   `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                   `item_id` bigint DEFAULT NULL COMMENT '关联实验/实践项目ID',
                                                   `assessment_category` tinyint DEFAULT NULL COMMENT '考核类别：1终结性 2形成性 3实验项目 4训练课目 5成果评价',
                                                   `assessment_item` varchar(255) DEFAULT NULL COMMENT '考核项目或成果形式',
                                                   `method` varchar(255) DEFAULT NULL COMMENT '考核方式',
                                                   `mechanism` varchar(255) DEFAULT NULL COMMENT '评定机制',
                                                   `score_system` varchar(100) DEFAULT NULL COMMENT '成绩评定：百分制/五级制/两级制',
                                                   `outcome_type` tinyint DEFAULT 0 COMMENT '成果类型字典 sys_plan_outcome_type：0无 1个人成果 2团队成果 3过程成果',
                                                   `assessed_content` text COMMENT '评价的知识和能力',
                                                   `weight` decimal(6,2) DEFAULT NULL COMMENT '权重',
                                                   `standard` longtext COMMENT '评价标准/评价准则',
                                                   `sort` int DEFAULT 1 COMMENT '排序',
                                                   `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                   `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                   `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                   `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                   `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                   `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                   PRIMARY KEY (`id`),
                                                   KEY `idx_tp_assess_plan` (`plan_id`),
                                                   KEY `idx_tp_assess_item` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划考核评价';

CREATE TABLE `t_csys_teaching_plan_textbook` (
                                                 `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                 `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                 `material_nature` varchar(100) DEFAULT NULL COMMENT '教材性质',
                                                 `name` varchar(255) DEFAULT NULL COMMENT '教材名称',
                                                 `first_author` varchar(100) DEFAULT NULL COMMENT '第一作者',
                                                 `edition` varchar(100) DEFAULT NULL COMMENT '版次',
                                                 `publisher` varchar(255) DEFAULT NULL COMMENT '出版或颁发单位',
                                                 `publish_time` varchar(50) DEFAULT NULL COMMENT '出版或颁发时间',
                                                 `isbn` varchar(100) DEFAULT NULL COMMENT 'ISBN号或统一书号/文件号',
                                                 `publish_method` varchar(100) DEFAULT NULL COMMENT '出版方式',
                                                 `sort` int DEFAULT 1 COMMENT '排序',
                                                 `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                 `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                 `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                 `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                 `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                 `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                 PRIMARY KEY (`id`),
                                                 KEY `idx_tp_textbook_plan` (`plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划教材';

CREATE TABLE `t_csys_teaching_plan_condition` (
                                                  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                  `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                  `condition_type` varchar(100) NOT NULL COMMENT '条件类型',
                                                  `requirement` longtext COMMENT '有关要求',
                                                  `sort` int DEFAULT 1 COMMENT '排序',
                                                  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                  `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                  `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                  `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                  PRIMARY KEY (`id`),
                                                  KEY `idx_tp_condition_plan` (`plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划条件保障';

CREATE TABLE `t_csys_teaching_plan_ref` (
                                            `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                            `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                            `context_id` bigint DEFAULT NULL COMMENT '调用上下文ID，可为空',
                                            `ref_type` tinyint NOT NULL COMMENT '引用类型：1支撑总库课程 2支撑调用课程/训练课目 3知识单元 4知识点 5教学目标',
                                            `ref_id` bigint DEFAULT NULL COMMENT '引用对象ID',
                                            `ref_name` varchar(500) DEFAULT NULL COMMENT '引用对象名称快照',
                                            `ref_hours` decimal(8,2) DEFAULT NULL COMMENT '引用课程/课目学时快照',
                                            `sort` int DEFAULT 1 COMMENT '排序',
                                            `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                            `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                            `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                            `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                            `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                            `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                            PRIMARY KEY (`id`),
                                            KEY `idx_tp_ref_plan` (`plan_id`),
                                            KEY `idx_tp_ref_context` (`context_id`),
                                            KEY `idx_tp_ref_type` (`ref_type`,`ref_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划通用引用';

CREATE TABLE `t_csys_teaching_plan_process_step` (
                                                     `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                                     `plan_id` bigint NOT NULL COMMENT '教学计划ID',
                                                     `item_id` bigint DEFAULT NULL COMMENT '关联实践项目ID',
                                                     `stage_name` varchar(255) DEFAULT NULL COMMENT '步骤分组；实践训练课目存实施步骤类别编码，实践项目可存阶段名称',
                                                     `step_name` varchar(255) DEFAULT NULL COMMENT '步骤明细；实践训练课目存阶段划分，实践项目存项目步骤',
                                                     `requirement` longtext COMMENT '有关要求',
                                                     `sort` int DEFAULT 1 COMMENT '排序',
                                                     `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                     `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
                                                     `last_modified_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                     `last_modifier` varchar(64) DEFAULT NULL COMMENT '更新人',
                                                     `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                                     `sysflag` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '删除标识',
                                                     PRIMARY KEY (`id`),
                                                     KEY `idx_tp_step_plan` (`plan_id`),
                                                     KEY `idx_tp_step_item` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='教学计划实施步骤';
